=== cbleek/arbeitsagentur-schema/studienfelder.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:complexType name="studienfeld-type">
		<xs:sequence>
			<xs:element name="beruf" type="beruf-type" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attributeGroup ref="studienfeldAttributes"/>
	</xs:complexType>
	<xs:complexType name="beruf-type">
		<xs:attributeGroup ref="berufAttributes"/>
	</xs:complexType>
	<xs:attributeGroup name="studienfeldAttributes">
		<xs:attribute name="id" type="xs:integer" use="required"/>
		<xs:attribute name="schluessel" type="xs:string" use="required"/>
		<xs:attribute name="bezeichnung" type="xs:string" use="required"/>
	</xs:attributeGroup>
	<xs:attributeGroup name="berufAttributes">
		<xs:attribute name="idref" use="required"/>
	</xs:attributeGroup>
	<xs:element name="studienfelder">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="studienfeld" type="studienfeld-type" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== cbleek/arbeitsagentur-schema/studienfelder.xml
<?xml version="1.0" encoding="UTF-8"?><studienfelder xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="studienfelder.xsd">
  <studienfeld id="93796" schluessel="HA 2101" bezeichnung="Agrarwissenschaften">
    <beruf idref="93711"/>
    <beruf idref="93756"/>
    <beruf idref="93870"/>
    <beruf idref="94180"/>
    <beruf idref="94368"/>
    <beruf idref="131692"/>
    <beruf idref="131694"/>
    <beruf idref="27375"/>
    <beruf idref="32433"/>
    <beruf idref="27677"/>
    <beruf idref="97356"/>
    <beruf idref="96890"/>
    <beruf idref="97676"/>
    <beruf idref="95090"/>
    <beruf idref="94732"/>
    <beruf idref="94763"/>
    <beruf idref="95374"/>
    <beruf idref="95422"/>
    <beruf idref="95172"/>
    <beruf idref="94996"/>
    <beruf idref="99865"/>
    <beruf idref="100430"/>
    <beruf idref="98147"/>
    <beruf idref="98565"/>
    <beruf idref="98336"/>
    <beruf idref="98107"/>
    <beruf idref="120420"/>
    <beruf idref="124545"/>
    <beruf idref="124546"/>
    <beruf idref="128203"/>
    <beruf idref="128235"/>
    <beruf idref="131232"/>
    <beruf idref="131233"/>
    <beruf idref="131238"/>
    <beruf idref="131693"/>
    <beruf idref="131695"/>
    <beruf idref="133815"/>
    <beruf idref="133816"/>
    <beruf idref="135032"/>
    <beruf idref="135034"/>
    <beruf idref="137778"/>
    <beruf idref="137779"/>
    <beruf idref="137780"/>
    <beruf idref="137782"/>
    <beruf idref="137783"/>
    <beruf idref="136678"/>
  </studienfeld>
  <studienfeld id="93986" schluessel="HA 2103" bezeichnung="Ernährungswissenschaften">
    <beruf idref="93917"/>
    <beruf idref="27607"/>
    <beruf idref="34933"/>
    <beruf idref="35293"/>
    <beruf idref="96159"/>
    <beruf idref="96928"/>
    <beruf idref="96948"/>
    <beruf idref="96361"/>
    <beruf idref="95150"/>
    <beruf idref="99657"/>
    <beruf idref="100503"/>
    <beruf idref="98013"/>
    <beruf idref="120590"/>
    <beruf idref="123562"/>
    <beruf idref="124744"/>
    <beruf idref="124745"/>
    <beruf idref="124746"/>
    <beruf idref="124747"/>
    <beruf idref="129808"/>
    <beruf idref="130594"/>
    <beruf idref="131537"/>
    <beruf idref="135260"/>
    <beruf idref="136938"/>
    <beruf idref="137969"/>
    <beruf idref="137970"/>
  </studienfeld>
  <studienfeld id="94014" schluessel="HA 2105" bezeichnung="Forstwissenschaften, -wirtschaft">
    <beruf idref="94279"/>
    <beruf idref="124273"/>
    <beruf idref="97375"/>
    <beruf idref="97403"/>
    <beruf idref="96938"/>
    <beruf idref="97437"/>
    <beruf idref="96631"/>
    <beruf idref="96790"/>
    <beruf idref="95477"/>
    <beruf idref="99940"/>
    <beruf idref="101446"/>
    <beruf idref="99454"/>
    <beruf idref="132755"/>
  </studienfeld>
  <studienfeld id="94010" schluessel="HA 2107" bezeichnung="Garten-, Landschaftsbau">
    <beruf idref="94289"/>
    <beruf idref="27581"/>
    <beruf idref="97022"/>
    <beruf idref="94742"/>
    <beruf idref="94791"/>
    <beruf idref="99728"/>
    <beruf idref="100200"/>
    <beruf idref="120421"/>
    <beruf idref="128132"/>
    <beruf idref="135038"/>
  </studienfeld>
  <studienfeld id="94329" schluessel="HA 2109" bezeichnung="Lebensmittel-, Getränketechnologie">
    <beruf idref="93615"/>
    <beruf idref="93769"/>
    <beruf idref="97378"/>
    <beruf idref="97388"/>
    <beruf idref="97471"/>
    <beruf idref="95690"/>
    <beruf idref="94696"/>
    <beruf idref="95980"/>
    <beruf idref="101083"/>
    <beruf idref="100109"/>
    <beruf idref="101299"/>
    <beruf idref="101034"/>
    <beruf idref="98171"/>
    <beruf idref="98598"/>
    <beruf idref="99051"/>
    <beruf idref="99517"/>
    <beruf idref="98671"/>
    <beruf idref="98303"/>
    <beruf idref="98311"/>
    <beruf idref="98744"/>
    <beruf idref="98548"/>
    <beruf idref="122406"/>
    <beruf idref="123588"/>
    <beruf idref="127940"/>
    <beruf idref="128173"/>
    <beruf idref="131318"/>
    <beruf idref="132802"/>
    <beruf idref="132803"/>
    <beruf idref="135093"/>
    <beruf idref="135094"/>
  </studienfeld>
  <studienfeld id="93936" schluessel="HA 2301" bezeichnung="Architektur, Raumplanung">
    <beruf idref="93960"/>
    <beruf idref="94136"/>
    <beruf idref="94138"/>
    <beruf idref="94326"/>
    <beruf idref="129598"/>
    <beruf idref="5087"/>
    <beruf idref="27856"/>
    <beruf idref="97331"/>
    <beruf idref="96929"/>
    <beruf idref="96677"/>
    <beruf idref="96292"/>
    <beruf idref="97116"/>
    <beruf idref="96070"/>
    <beruf idref="95346"/>
    <beruf idref="94816"/>
    <beruf idref="95409"/>
    <beruf idref="95133"/>
    <beruf idref="95582"/>
    <beruf idref="96016"/>
    <beruf idref="99856"/>
    <beruf idref="99933"/>
    <beruf idref="99939"/>
    <beruf idref="100040"/>
    <beruf idref="100073"/>
    <beruf idref="99730"/>
    <beruf idref="99483"/>
    <beruf idref="97792"/>
    <beruf idref="97918"/>
    <beruf idref="98408"/>
    <beruf idref="98457"/>
    <beruf idref="98906"/>
    <beruf idref="98911"/>
    <beruf idref="98930"/>
    <beruf idref="98512"/>
    <beruf idref="124624"/>
    <beruf idref="127770"/>
    <beruf idref="127771"/>
    <beruf idref="127647"/>
    <beruf idref="127667"/>
    <beruf idref="127965"/>
    <beruf idref="131242"/>
    <beruf idref="134170"/>
    <beruf idref="133894"/>
    <beruf idref="133895"/>
    <beruf idref="135101"/>
  </studienfeld>
  <studienfeld id="94030" schluessel="HA 2303" bezeichnung="Automatisierungs-, Produktionstechnik">
    <beruf idref="93697"/>
    <beruf idref="94202"/>
    <beruf idref="94247"/>
    <beruf idref="129545"/>
    <beruf idref="129546"/>
    <beruf idref="129573"/>
    <beruf idref="129574"/>
    <beruf idref="125604"/>
    <beruf idref="30228"/>
    <beruf idref="51055"/>
    <beruf idref="15713"/>
    <beruf idref="97293"/>
    <beruf idref="97762"/>
    <beruf idref="96467"/>
    <beruf idref="96726"/>
    <beruf idref="96749"/>
    <beruf idref="97609"/>
    <beruf idref="97639"/>
    <beruf idref="96394"/>
    <beruf idref="97154"/>
    <beruf idref="96112"/>
    <beruf idref="95296"/>
    <beruf idref="94698"/>
    <beruf idref="94870"/>
    <beruf idref="95981"/>
    <beruf idref="95225"/>
    <beruf idref="96033"/>
    <beruf idref="99033"/>
    <beruf idref="99131"/>
    <beruf idref="97840"/>
    <beruf idref="98352"/>
    <beruf idref="97957"/>
    <beruf idref="98813"/>
    <beruf idref="97964"/>
    <beruf idref="98488"/>
    <beruf idref="98950"/>
    <beruf idref="98965"/>
    <beruf idref="101514"/>
    <beruf idref="101545"/>
    <beruf idref="120444"/>
    <beruf idref="120468"/>
    <beruf idref="124576"/>
    <beruf idref="124577"/>
    <beruf idref="124578"/>
    <beruf idref="124579"/>
    <beruf idref="124580"/>
    <beruf idref="124581"/>
    <beruf idref="124582"/>
    <beruf idref="124603"/>
    <beruf idref="124604"/>
    <beruf idref="124612"/>
    <beruf idref="130383"/>
    <beruf idref="130384"/>
    <beruf idref="130404"/>
    <beruf idref="130408"/>
    <beruf idref="127920"/>
    <beruf idref="128216"/>
    <beruf idref="127916"/>
    <beruf idref="127945"/>
    <beruf idref="127946"/>
    <beruf idref="127954"/>
    <beruf idref="127964"/>
    <beruf idref="127972"/>
    <beruf idref="131265"/>
    <beruf idref="131266"/>
    <beruf idref="131267"/>
    <beruf idref="132775"/>
    <beruf idref="132790"/>
    <beruf idref="133843"/>
    <beruf idref="133844"/>
    <beruf idref="133845"/>
    <beruf idref="133846"/>
    <beruf idref="136731"/>
    <beruf idref="136732"/>
    <beruf idref="136736"/>
    <beruf idref="135053"/>
    <beruf idref="135054"/>
    <beruf idref="135087"/>
    <beruf idref="135088"/>
    <beruf idref="137792"/>
    <beruf idref="137793"/>
  </studienfeld>
  <studienfeld id="93819" schluessel="HA 2305" bezeichnung="Bautechnik">
    <beruf idref="93676"/>
    <beruf idref="94113"/>
    <beruf idref="129594"/>
    <beruf idref="5081"/>
    <beruf idref="14273"/>
    <beruf idref="32435"/>
    <beruf idref="97291"/>
    <beruf idref="96502"/>
    <beruf idref="96529"/>
    <beruf idref="96579"/>
    <beruf idref="96589"/>
    <beruf idref="96331"/>
    <beruf idref="97119"/>
    <beruf idref="95684"/>
    <beruf idref="95223"/>
    <beruf idref="94999"/>
    <beruf idref="101103"/>
    <beruf idref="100920"/>
    <beruf idref="99894"/>
    <beruf idref="100340"/>
    <beruf idref="100413"/>
    <beruf idref="101197"/>
    <beruf idref="100996"/>
    <beruf idref="101240"/>
    <beruf idref="101009"/>
    <beruf idref="99105"/>
    <beruf idref="99384"/>
    <beruf idref="101511"/>
    <beruf idref="120481"/>
    <beruf idref="120482"/>
    <beruf idref="120483"/>
    <beruf idref="123570"/>
    <beruf idref="124622"/>
    <beruf idref="130419"/>
    <beruf idref="130420"/>
    <beruf idref="127670"/>
    <beruf idref="128085"/>
    <beruf idref="131319"/>
    <beruf idref="131320"/>
    <beruf idref="133889"/>
    <beruf idref="136740"/>
    <beruf idref="136741"/>
    <beruf idref="136742"/>
    <beruf idref="135096"/>
    <beruf idref="137820"/>
    <beruf idref="137821"/>
  </studienfeld>
  <studienfeld id="136538" schluessel="HA 2306" bezeichnung="Chemietechnik">
    <beruf idref="93665"/>
    <beruf idref="93742"/>
    <beruf idref="94396"/>
    <beruf idref="51060"/>
    <beruf idref="14727"/>
    <beruf idref="32409"/>
    <beruf idref="96838"/>
    <beruf idref="96877"/>
    <beruf idref="97407"/>
    <beruf idref="96904"/>
    <beruf idref="97507"/>
    <beruf idref="96264"/>
    <beruf idref="95646"/>
    <beruf idref="96111"/>
    <beruf idref="94669"/>
    <beruf idref="101117"/>
    <beruf idref="99891"/>
    <beruf idref="100449"/>
    <beruf idref="101037"/>
    <beruf idref="98623"/>
    <beruf idref="97820"/>
    <beruf idref="98688"/>
    <beruf idref="97839"/>
    <beruf idref="98787"/>
    <beruf idref="98021"/>
    <beruf idref="98118"/>
    <beruf idref="120496"/>
    <beruf idref="124640"/>
